name: Environmental Station Alpha
comment: ''
sub-series: []
randomizers:
-   game: Environmental Station Alpha
    url: https://www.speedrun.com/esalpha/resources
    identifier: Mokesmoe's
    original: '- [Environmental Station Alpha](https://www.speedrun.com/esalpha/resources)
        (Mokesmoe''s) - Located under Tools'
    comment: '- Located under Tools'
