name: Schema Checks
on: [push, pull_request]
jobs:
  Schema_Checks:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: switching from HTTPS to SSH
        run: git remote set-url --add origin ${{ secrets.ssh }}

      - name: edit file
        run: date > test.txt
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating file"
      - name: fetch from main
        run: git fetch origin main
      - name: push code to main
        run: git push --force
      
      - run: cd ${{ github.workspace }}

      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
            cache: 'pip' # caching pip dependencies
      - run: pip3 install -r src/requirements.txt 2>&1

      - run: python -m compileall -q src
      - run: python3 schemaCheck.py
        working-directory: ./src

      - run: echo "🍏 This job's status is ${{ job.status }}."
